/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_machineswithvision_openvx_JOVX */

#ifndef _Included_com_machineswithvision_openvx_JOVX
#define _Included_com_machineswithvision_openvx_JOVX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_machineswithvision_openvx_JOVX
 * Method:    jovxCreateContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_machineswithvision_openvx_JOVX_jovxCreateContext
  (JNIEnv *, jclass);

/*
 * Class:     com_machineswithvision_openvx_JOVX
 * Method:    processBytes
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_com_machineswithvision_openvx_JOVX_processBytes
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_machineswithvision_openvx_JOVX
 * Method:    jovxReleaseContext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_machineswithvision_openvx_JOVX_jovxReleaseContext
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
